Update pipe-it-2cluster.yml

diff --git a/.github/workflows/pipe-it-2cluster.yml b/.github/workflows/pipe-it-2cluster.yml
--- a/.github/workflows/pipe-it-2cluster.yml
+++ b/.github/workflows/pipe-it-2cluster.yml
@@ -211,16 +211,24 @@ jobs:
               -DClusterConfigurations=${{ matrix.cluster1 }},${{ matrix.cluster2 }} \
               -pl integration-test \
               -am -PMultiClusterIT2SubscriptionArchVerification \
-              -ntp && return 0
-            if [ $attempt -lt $max_attempts ]; then
-              echo "Test failed, attempt $attempt. Retrying in $retry_sleep seconds..."
-              sleep $retry_sleep
-            else
-              echo "Test failed after $max_attempts attempts."
-              return 1
-            fi
-          
-            attempt=$((attempt + 1))
+              -ntp && return 0 >> ~/run-tests.log
+              test_output=$(cat ~/run-tests.log) 
+              if echo "$test_output" | grep -q "Could not transfer artifact"; then
+                if [ $attempt -lt $max_attempts ]; then
+                  echo "Test failed with artifact transfer issue, attempt $attempt. Retrying in $retry_sleep seconds..."
+                  sleep $retry_sleep
+                  attempt=$((attempt + 1))
+                else
+                  echo "Test failed after $max_attempts attempts due to artifact transfer issue."
+                  return 1
+                fi
+              elif [ $? -ne 0 ]; then
+                echo "Test failed with a different error."
+                return 1
+              else
+                echo "Tests passed"
+                return 0
+              fi
             done
           }
           retry
